In [2]:
#1. Numpy array starting from 2 till 50 with step size 3

import numpy as np

l1 = [i for i in range(2,51,3)]
arr = np.array(l1)
print(arr)


[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47 50]


In [59]:
#2. Accept 2 list of 5 elements from user, convert them into numpy arrays, concatenate and print. Sort and print

list_1 = [int(i) for i in input("1st list 5 no.s:").split()]
list_2 = [int(i) for i in input("2nd list 5 no.s:").split()]

#arr_1 = np.array(list_1)
#arr_2 = np.array(list_2)
arr_n = np.concatenate((np.array(list_1),np.array(list_2)),axis=0)
print(arr_n)
print(np.sort(arr_n))


1st list 5 no.s:1 2 3 4 5
2nd list 5 no.s:24 43 12 56 12
[ 1  2  3  4  5 24 43 12 56 12]
[ 1  2  3  4  5 12 12 24 43 56]


In [32]:
#3.Code snippet to find the dimension of ndarray and its size

#np.ndim(arr) #dimesion could be understood as the no. of co-ordinates required for reaching the base element.
#np.size(arr) #size is the total no. of base elements in an array

#Sample eg. 
arr_dim = np.arange(24)

arr2 = arr_dim.reshape(6,4)
print(np.ndim(arr2))
print(np.size(arr2))


2
24


In [57]:
#4. Convert 1D Array to 2D Array

arr_1d = np.arange(8)
print(arr_1d,"Dimesion of the array:",np.ndim(arr_1d),"Shape of the array:",np.shape(arr_1d))

print()

#using reshape to convert from 1D to 2D
arr_2d = arr_1d.reshape(2,4)
print("RESHAPE \n",arr_2d,"\n Dimesion of the array:",np.ndim(arr_2d),"\n Shape of the array:",np.shape(arr_2d))
print()

#using np.newaxis
arr_2D = arr_1d[:,np.newaxis]
print("NEWAXIS \n",arr_2D,"\n Dimesion of the array:",np.ndim(arr_2D),"\n Shape of the array:",np.shape(arr_2D))
print()

#using np.expand_dims
arr_2D1 = np.expand_dims(arr_1d, axis = 0)
print("EXPAND DIMS \n",arr_2D1,"\n Dimesion of the array:",np.ndim(arr_2D1),"\n Shape of the array:",np.shape(arr_2D1))


[0 1 2 3 4 5 6 7] Dimesion of the array: 1 Shape of the array: (8,)

RESHAPE 
 [[0 1 2 3]
 [4 5 6 7]] 
 Dimesion of the array: 2 
 Shape of the array: (2, 4)

NEWAXIS 
 [[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]] 
 Dimesion of the array: 2 
 Shape of the array: (8, 1)

EXPAND DIMS 
 [[0 1 2 3 4 5 6 7]] 
 Dimesion of the array: 2 
 Shape of the array: (1, 8)


In [85]:
#5. 2square NUMPY arrays , stack them horizontally and vertically

sqarr1 = np.square(np.array([1,2,3]))
sqarr2 = np.square(np.array([4,5,6]))

a = np.vstack((sqarr1, sqarr2))
b = np.hstack((sqarr1, sqarr2))
print("Horizontal \n",b)
print()
print("Vertical \n",a)



Horizontal 
 [ 1  4  9 16 25 36]

Vertical 
 [[ 1  4  9]
 [16 25 36]]


In [98]:
#6. Get Unique items and count of unique items

arr_u = np.array(input("Enter your no.s for array:").split())

arr_temp = np.unique(arr_u)
arr_size = np.size(arr_temp)

print(arr_temp)
print()
print(arr_size)


Enter your no.s for array:1 2 2 3 3 232 12 21 12 23
['1' '12' '2' '21' '23' '232' '3']

7
